### ISSUE TITLE
Support font ligatures

### ISSUE THREAD

**Issue by vhanla** [Alexey-T/ATSynEdit#148]
As a feature request, Would it be possible to allow certain common symbols in programming fonts like Fira Code, Monoid. Operator Mono, etc. as modern editors do? 

Most modern editors includes support for ligatures out of the box, like Atom e.g.

![example](https://cdn-images-1.medium.com/max/600/1*wP6e1QtYkm5ezm8QLA8wkA.gif)

> This animation shows how some programming language characters are replaced by a ligature which gives a more intuitive symbol instead.

It eases the reading and if the editor supports multiple font files it can even be customized to give it a nicer look. 

![example2](https://cdn-images-1.medium.com/max/1000/1*xpk3jvJK1-JpaK6Gz-IlMA.png)

> In this picture there were used different fonts to render special language keywords, functions, etc. depending on how it was configured, resulting in a more modern look.

Hope you take this feature request into consideration for future features on this awesome component.

Sources:
 [An alternative to Operator Mono](https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e#.bj3uwd1jh)
[Ligatures and Coding](https://medium.com/larsenwork-andreas-larsen/ligatures-coding-fonts-5375ab47ef8e#.fnl12the8)

**Comment by Alexey-T** [comment]
It is possible later,not now, code dont know this. code needs to replace n chars to  1 unicode char? to bitmap? to what? only if caret not on this line?

**Comment by Alexey-T** [comment]
I see Ububtu ALREADY does this painting-
What OS you need?
![fira](https://cloud.githubusercontent.com/assets/4154978/22248823/dd341988-e259-11e6-9dbc-01dbc22a7bc3.png)

**Comment by Alexey-T** [comment]
@kvichans: Maybe interesting for Win?

**Comment by Alexey-T** [comment]
for Win32 it's needed. cannot find what Unicode codes to use-
- for "->", "-->", "<=>" etc. Give the info pls?

**Comment by vhanla** [comment]
FiraCode font uses OpenType's Contextual Alternates for their ligatures, but they also mention that another method would be using OpenType's Liga feature. "They both gets compiled to GSUB (glyph substitution table)." as they told me.

Sources:
[GSUB Glyph Substitution Table](https://www.microsoft.com/typography/otspec/GSUB.htm)
[Contextual Alternates in Adobe apps](https://www.fontshop.com/content/enable-contextual-alternates)
[Advanced Contextual Alternates](https://www.glyphsapp.com/tutorials/features-part-3-advanced-contextual-alternates)
[OpenType Font Features](https://msdn.microsoft.com/en-us/library/ms745109%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

**Comment by Alexey-T** [comment]
this do not help me. I need not inf about fonts. I need api, how to calc Unicode code (int) for ligature (e.g. "-->")
I cannot find api. in win32 or linux.

**Comment by vhanla** [comment]
As I understand, there seems that those fonts' ligatures are rendered using Uniscribe API on Windows (ATSUI on OSX) to locate GSUB and GPOS tables so the strings are matched correctly. I found this project written in C# https://github.com/LayoutFarm/Typography which might lead to the correct implementation, as it seems it is not only a matter of matching strings by hardcoding their equivalents, but by using those OpenType's font features.

I might be wrong, but that is how it is supposed to be rendered, as far as I can tell. I will be doing more research on this.

**Comment by Alexey-T** [comment]
in unit for uniscribe API, I need to find part, which can find ligatures. e.g. "-->". and find Unicode char for "-->". then I can paint unicode char, instead of string "-->"

**Comment by Alexey-T** [comment]
@vhanla 
To do this issue, need all pairs:
(ascii_string, unicode_code_of_ligature)
can you find all pairs?

**Comment by vhanla** [comment]
@Alexey-T There is no need to do that, at least on Windows, because `drawtext` does it for you, instead of `ExtTextOut`. 

I just modified `AT_SynEdit_CanvasProc.pas` file, and replaced the last `CanvasTextOut` call by       
```cpp
DrawText(C.Handle,PChar(Buf), Length(Buf),PartRect, DT_NOCLIP);
```
However, I couldn't figure out how to align it correctly when TAB Chars are entered:

![demo](https://i.imgur.com/ceMXxkH.png)

I'm not sure if `ExtTextOut` is faster than `DrawText`, but it would be optional which one to choose, allowing us which procedure to use. 

For instance, we can disable it when caret is on current line and only show the normal text, but enabled on the other lines, as shown in the GIF above (first comment).

**Comment by Alexey-T** [comment]
Strange that Drawtext gives bad with tabs: afaik I paint n spaces for each tab (not chr9)
W/o fixing it- cannot use

**Comment by vhanla** [comment]
Instead of converting Tabs to Spaces, it was left unmodified and I used DrawTextEx with DT_TABSTOP + DT_EXPANDTABS +  DRAWTEXTPARAMS (to specify ATabSize), the modified code can be found at [this fork](https://github.com/vhanla/ATSynEdit/commit/acd2f09ee4d7d5ddb4a37b7681d6d1b06323ae64) : 
![tab](https://i.imgur.com/GIP39UN.png)
I don't know it that would correct, needs further testing, but at least on Windows, it fixes the ligatures issue. 

BTW, (unrelated to this issue), I noticed that composite characters such as `ñ` ,(`´` + `a` <> `á`) , etc. is not working and shows a weird character, regardless of ExtTextOut or DrawTextEx usage, but `Ctrl+C` and `Ctrl+V` copies/pastes correctly.

**Comment by vhanla** [comment]
All right, after trying `ExtTextOut` on Delphi and Lazarus 1.6.4, there seems that Lazarus has it implemented in a different way. Because with Delphi, `ExtTextOut` renders text with ligatures.

However, Lazarus renders perfectly only using DrawText (not from windows unit, but the multiplatform unit `redef.inc`), but failing with ExtTextOut, this test was done on Windows, on Linux it doesn't have that issue.

So, if that `ExtTextOut` implementation in Lazarus were fixed, it wouldn't have been necessary those changes I did previously.

Anyway, at least now it shows ligatures on Windows. Hopefully, the guys behind Lazarus/FPC will fix it.

**Comment by Alexey-T** [comment]
> if that ExtTextOut implementation in Lazarus were fixed, it wouldn't have been necessary those changes I did previously.

Yes, it is right, Lazarus needs fix in ExtTextOut, and big patch not needed now
Imo Lazarus misses some int flag to call Win32 api ExtTextout.
Need to see.

**Comment by Alexey-T** [comment]
fixed in https://github.com/Alexey-T/ATSynEdit/commit/94ceacad1089408a7c724dc3f8a6c0d6be2fb157

**Comment by vhanla** [comment]
Even though this issue has been fixed, I guess it is worth to spread this answer that somebody gave me at [Lazarus FPC forum](http://forum.lazarus.freepascal.org/index.php/topic,36522.0.html) regarding to the usage of ExtTextOut with [ETO_GLYPH_INDEX ](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162713(v=vs.85).aspx) flag along with  [GetCharPlacement](https://msdn.microsoft.com/en-us/library/windows/desktop/dd144860(v=vs.85).aspx) function, so here it is:

```pascal
var
  R: TRect;
  Msg: AnsiString;
  CharPlaceInfo: TGCPResults; //use Windows
  Glyphs: array of WideChar;
begin
  R.Left := 12;
  R.Top := 12;
  R.Width := 400;
  R.Bottom := 100;
  Msg := '   <!-- tag html -->';
  ZeroMemory(@CharPlaceInfo, SizeOf(CharPlaceInfo));
  CharPlaceInfo.lStructSize := SizeOf(CharPlaceInfo);
  SetLength(Glyphs, Length(Msg));
  CharPlaceInfo.lpGlyphs := @Glyphs[0];
  CharPlaceInfo.nGlyphs := Length(Glyphs);
  if GetCharacterPlacement(Canvas.Handle, PChar(Msg), Length(Msg), 0, @CharPlaceInfo, GCP_LIGATE) <> 0 then
  begin
    ExtTextOut(Canvas.Handle, R.Left, R.Top, ETO_CLIPPED or ETO_OPAQUE or ETO_GLYPH_INDEX, @R, Pointer(Glyphs), Length(Glyphs), nil);
  end;
```
And according to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162490(v=vs.85).aspx):

> An application will achieve the fastest execution by calling ExtTextOut, which is quickly converted into an ExtTextOut call for the device. 

I have test it, and the text is shown with ligatures.

**Comment by Alexey-T** [comment]
Maybe slower a little: now call to GetCharPlacements+ExtTextOut
maybe I keep my code (Drawtext).

**Comment by Alexey-T** [comment]
I dunno how to use it with Dx parameter. If not use Dx, cannot paint ok width for CJK chars.

**Comment by vhanla** [comment]
`DrawText` has issues with `spacing-x` so I tried modifying `_SelfTextOut` as follows: 
```pascal
function _SelfTextOut(DC: HDC; X, Y: Integer; Rect: PRect;
  const Str: String;
  Dx: PInteger;
  AllowLigatures: boolean
  ): boolean;
//override LCLIntf.ExtTextOut, on Win32 use DrawText to draw font ligatures
//(Windows.ExtTextOut cannot)
var
  CharPlaceInfo: TGCPRESULTS;
  Glyphs: array of WideChar;
begin
  {$ifdef windows}
  if AllowLigatures then
  begin
    ZeroMemory(@CharPlaceInfo, SizeOf(CharPlaceInfo));
    CharPlaceInfo.lStructSize := SizeOf(CharPlaceInfo);
    SetLength(Glyphs, Length(Str));
    CharPlaceInfo.lpGlyphs := @Glyphs[0];
    CharPlaceInfo.nGlyphs := Length(Glyphs);

    if GetCharacterPlacement(DC, PChar(Str), Length(Str), 0, @CharPlaceInfo, GCP_LIGATE)<> 0 then
      Result := WINDOWS.ExtTextOut(DC, X, Y, ETO_CLIPPED or ETO_OPAQUE or ETO_GLYPH_INDEX, Rect, Pointer(Glyphs), Length(Glyphs), Dx)
    else
      Result:= ExtTextOut(DC, X, Y, ETO_CLIPPED+ETO_OPAQUE, Rect, PChar(Str), Length(Str), Dx);
  end
  else
  {$endif}
  Result:= ExtTextOut(DC, X, Y, ETO_CLIPPED+ETO_OPAQUE, Rect, PChar(Str), Length(Str), Dx);
end;
```
And now it shows as the following snapshot:
![img](https://i.imgur.com/VNoRrmo.png)

Notice that ExtTextOut with Glyphs is `Windows.ExtTextOut` and without Glyphs is `LCLInf.ExtTextOut`  implicitly.

I guess it needs code optimization, but at least it fixes the Dx parameter issue for custom horizontal spacing.

**Comment by Alexey-T** [comment]
Applied. Tks.
ps.
I still see issue, on SpacingX>2, in Demo Editor, on Linux. lines "wwww" paint narrow.
